version: "3.8"

services:
  rk-frontend:
    image: frontend
    container_name: rk-frontend
    ports:
      - 3000:3000
    networks:
      - reactapp
    depends_on:
      - rk-backend
    environment:
      - REACT_APP_BASE_URL=http://65.0.19.153:5000/api

  rk-backend:
    image: backend
    container_name: rk-backend
    ports:
      - 5000:5000
    networks:
      - reactapp
    depends_on:
      - mongodb
    environment:
      - DB=mongodb://mongo:27017/mydb

  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - reactapp
    volumes:
      - mongo-data:/data/db
    

networks:
  reactapp:


volumes:
  mongo-data:
